export const START_SIMPLE_SEARCH = '[MY_PROJ][FASHION] START_SIMPLE_SEARCH';
export const START_SEARCH_CURRENCY = '[MY_PROJ][FASHION] START_SEARCH_CURRENCY';
export const START_SEARCH_PRICE = '[MY_PROJ][FASHION] START_SEARCH_PRICE';
export const START_SEARCH_RETAILER = '[MY_PROJ][FASHION] START_SEARCH_RETAILER';
export const START_SEARCH_BRAND = '[MY_PROJ][FASHION] START_SEARCH_BRAND';